### ISSUE TITLE
Hardcoded default /home/ path?

### ISSUE THREAD

**Issue by morgajel** [maestrodev/puppet-ssh_keygen#4]
It looks like your expect the home directory to be under /home, which obviously breaks for root and system accounts.

ssh-keygen -t rsa -b 2048 -f "/home/root/.ssh/id_rsa" -N '' -C 'root@myserver' returned 1 instead of one of [0]
Error: /Stage[main]/Users/Ssh_keygen[root]/Exec[ssh_keygen-root]/returns: change from notrun to 0 failed: ssh-keygen -t rsa -b 2048 -f "/home/root/.ssh/id_rsa" -N '' -C 'root@myserver'

**Comment by edestecd** [comment]
I think the stdlib has some facts to get the root/user home.
That might be useful.  I know we use these types of facts on a regular basis.

**Comment by fraenki** [comment]
This issue has already been fixed: https://github.com/maestrodev/puppet-ssh_keygen/commit/5b3cd749da5b9fce08bd32f339ec5d51b7e2a780.
I suggest to close this issue.
